global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'fastapi-backend'
    metrics_path: /metrics
    static_configs:
      - targets: ['backend:8000']
  - job_name: 'node-exporter'
    static_configs:
        - targets: ['nodeexporter:9100']
